### ISSUE TITLE
New repo

### ISSUE THREAD

**Issue by woshichenghaibo** [skylerwlewis/netlify-ddns#8]
https://github.com/woshichenghaibo/Netlify-DDNS

v4ddns.sh ACCESS_TOKEN DOMAIN SUBDOMAIN TTL [CACHED_IP_FILE]

or

v6ddns.sh ACCESS_TOKEN DOMAIN SUBDOMAIN TTL [CACHED_IP_FILE]

I would like to express my gratitude to @skylerwlewis here

skylerwlewis/netlify-ddns @ https://github.com/skylerwlewis/netlify-ddns

**Comment by skylerwlewis** [comment]
Very nice! Glad to hear this worked out for you. I can add a link to your repo from mine also.

**Comment by woshichenghaibo** [comment]
> Very nice! Glad to hear this worked out for you. I can add a link to your repo from mine also.

truly sorry for the Ipv6 script that sometimes write wrong text into the Log-file ...I'm going to check it and may you could do me a favor?
